-- Insert roles
INSERT INTO roles (rolename)
SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE rolename = 'ROLE_USER');

INSERT INTO roles (rolename)
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE rolename = 'ROLE_ADMIN');